---
baseurl: "https://deployo.me/"
languageCode: "en-us"
title: "Deployo"

menu:
    docs:
    - name: "Dashboard"
      identifier: "dashboard"
      weight: 1
      url: "/docs/dashboard/"
    - name: "Projects"
      identifier: "projects"
      weight: 1
      url: "/docs/projects/"
    - name: "Configuration"
      identifier: "configuration"
      weight: 2
      url: "/docs/configuration/"
    - name: "Executing"
      weight: 3
      identifier: "executing"
      url: "/docs/executing/"
    - name: "Secrets"
      weight: 4
      identifier: "secrets"
      url: "/docs/secrets/"
    - name: "SSH Keys"
      weight: 4
      identifier: "ssh_keys"
      url: "/docs/ssh_keys/"
    - name: "User"
      weight: 5
      identifier: "user"
      url: "/docs/user/"